## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "Orbifolds" );
LoadPackage( "IO_ForHomalg" );
HOMALG_IO.show_banners := false;
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "Orbifolds", "doc" )[1]![1], "Orbifolds.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "Orbifolds" );
QUIT;
